[package]
name = "textf"
authors = ["tafh-debug"]
description = "Crate for formatting text. Without any depenencies. Only my code."
version = "0.1.0"
edition = "2021"

[dependencies]

compress = "0.2.1" #For a while. Then someday I'll write it myself. (Not exactly)
plotters = "0.3.1"
